#ifndef NYAS_CONFIG_H
#define NYAS_CONFIG_H

#define NYAS_FRAME_ALLOCATOR_ARENA_SIZE (16 * 1024 * 1024)
#define NYAS_TEXUNIT_OFFSET_FOR_COMMON_SHADER_DATA (16)
#define NYAS_PIPELINE_MAX_UNITS 256

#define NYAS_TEX_ARRAY_SIZE 64
#define NYAS_TEX_ARRAYS 16
#define NYAS_CUBEMAP_ARRAY_SIZE 8
#define NYAS_CUBEMAP_ARRAYS 8

#define NYAS_INVALID_RESOURCE_ID 0
#define NYAS_INVALID_HANDLE -1

// #define NyDrawIdx unsigned int
// #define NyResourceID void*
// #define NYAS_ASSERT(_COND) assert(_COND)

#endif // NYAS_CONFIG_H
