#ifndef NYAS_CONFIG_H
#define NYAS_CONFIG_H

#define NYAS_FRAME_ALLOCATOR_ARENA_SIZE (16 * 1024 * 1024)
#define NYAS_TEXUNIT_OFFSET_FOR_COMMON_SHADER_DATA (8)
#define NYAS_PIPELINE_MAX_UNITS 1024

// #define NyDrawIdx unsigned int
// #define NYAS_ASSERT(_COND) assert(_COND)

#endif // NYAS_CONFIG_H
